version: '3.1'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - my-datavolume:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/webapp_sample
    ports:
      - "3000:3000"
    environment:
      DB_DATABASE: webapp_sample_development
      DB_USER: root
      DB_PASSWORD: password
      DB_HOST: db
      DB_PORT: 3306
    depends_on:
      - db
volumes:
  my-datavolume:
